"use client";
import { useParams } from "next/navigation"; import { DataWorkspace, Row } from "@/components/DataWorkspace";
const config:Record<string,{title:string;description:string;rows:Row[]}>={
 samples:{title:"Samples & Timepoints",description:"Track sample pulls, receipt, testing and retention across active studies.",rows:[{id:"SMP-004201",name:"AMX-26-008 · T6",meta:"30 Sep · 25°C / 60% RH · Cairo",status:"Scheduled",tone:"active"},{id:"SMP-004198",name:"PCM-26-014 · T3",meta:"21 Sep · 40°C / 75% RH · Giza",status:"Due",tone:"warning"}]},
 results:{title:"Results & Review",description:"Enter, review, approve and lock controlled analytical results.",rows:[{id:"RES-1837",name:"Assay · 99.2%",meta:"STB-2026-0042 · HPLC",status:"Pending QA",tone:"warning"},{id:"RES-1836",name:"Dissolution · 94%",meta:"STB-2026-0042 · USP",status:"Approved",tone:"active"},{id:"RES-1829",name:"Related substances",meta:"STB-2026-0041 · HPLC",status:"OOS",tone:"critical"}]},
 chambers:{title:"Stability Chambers",description:"Manage qualified chambers, conditions, capacity and environmental events.",rows:[{id:"CH-01",name:"Long-term chamber",meta:"25°C / 60% RH · Cairo · 82% capacity",status:"Qualified",tone:"active"},{id:"CH-04",name:"Accelerated chamber",meta:"40°C / 75% RH · Cairo · excursion",status:"Excursion",tone:"critical"}]},
 protocols:{title:"Protocols",description:"Controlled protocols and version history used by stability studies.",rows:[{id:"STB-PRO-003",name:"Amoxicillin stability protocol",meta:"3 versions · v2.1 effective",status:"Effective",tone:"active"},{id:"STB-PRO-002",name:"Paracetamol protocol",meta:"4 versions · v1.4 effective",status:"Effective",tone:"active"}]},
 specifications:{title:"Specifications",description:"Controlled specifications and effective versions for analytical requirements.",rows:[{id:"SPEC-019",name:"Amoxicillin release & stability",meta:"12 parameters · v3",status:"Effective",tone:"active"},{id:"SPEC-014",name:"Paracetamol stability",meta:"9 parameters · v4",status:"Under review",tone:"warning"}]},
 quality:{title:"OOS / OOT",description:"Quality event intake, investigation and controlled disposition.",rows:[{id:"OOS-2026-008",name:"Assay below specification",meta:"RES-1829 · Phase I investigation",status:"Open",tone:"critical"},{id:"OOT-2026-004",name:"Dissolution trend shift",meta:"STB-2026-0041 · QA review",status:"Review",tone:"warning"}]},
 deviations:{title:"Deviations",description:"Investigate departures from approved procedures and assess product impact.",rows:[{id:"DEV-2026-017",name:"Chamber excursion CH-04",meta:"Impact assessment in progress",status:"Open",tone:"critical"}]},
 capa:{title:"CAPA",description:"Manage corrective and preventive actions with owners, due dates and effectiveness checks.",rows:[{id:"CAPA-2026-011",name:"Environmental monitoring corrective action",meta:"Owner: QA · Due 30 Oct",status:"In progress",tone:"warning"}]},
 audit:{title:"Audit & Compliance",description:"Review immutable activity history, signatures, approvals and compliance evidence.",rows:[{id:"AUD-91831",name:"Protocol version approved",meta:"Ahmed Hassan · 15 Sep 2026 09:42",status:"Recorded",tone:"active"},{id:"AUD-91829",name:"Result corrected",meta:"Mona Ali · Reason captured",status:"Recorded",tone:"active"}]},
 "master-data":{title:"Products & Batches",description:"Controlled pharmaceutical master data and enrolled batches.",rows:[{id:"PRD-0042",name:"Amoxicillin 500 mg Capsules",meta:"3 strengths · 12 active batches",status:"Active",tone:"active"},{id:"BAT-026008",name:"AMX-26-008",meta:"Manufactured 12 Aug 2026 · Cairo",status:"Enrolled",tone:"active"}]},
 analytics:{title:"Reports & Analytics",description:"Executive, QA and operational views across the organization.",rows:[{id:"RPT-STABILITY",name:"Stability portfolio health",meta:"24 active studies · 7 due",status:"Ready",tone:"active"},{id:"RPT-QUALITY",name:"Quality events trend",meta:"OOS/OOT/deviation · 90 days",status:"Ready",tone:"active"}]},
 organization:{title:"Organization",description:"Manage company profile, sites, security and tenant-level configuration.",rows:[{id:"ORG-001",name:"Cairo Pharmaceutical Group",meta:"Egypt · EGP · Africa/Cairo",status:"Active",tone:"active"}]},
 users:{title:"Users & Roles",description:"Invite users, assign organization roles and control site access.",rows:[{id:"USR-001",name:"Ahmed Hassan",meta:"QA Manager · Cairo Site",status:"Active",tone:"active"},{id:"USR-002",name:"Mona Ali",meta:"Analyst · Cairo Site",status:"Active",tone:"active"}]},
 billing:{title:"Billing & Subscription",description:"Manage plan, usage, invoices and subscription lifecycle.",rows:[{id:"SUB-001",name:"Professional plan",meta:"23 / 50 users · 187 / 1000 studies",status:"Active",tone:"active"},{id:"INV-2026-09",name:"September 2026 invoice",meta:"Due 01 Oct 2026",status:"Open",tone:"warning"}]},
 settings:{title:"Settings",description:"Security, notifications, integrations and organization preferences.",rows:[{id:"SECURITY",name:"Security policy",meta:"MFA · sessions · authentication",status:"Configured",tone:"active"}]}
};
export default function Section(){const {section}=useParams<{section:string}>();const c=config[section]??{title:"QCSTS Workspace",description:"Controlled workspace.",rows:[]};return <DataWorkspace title={c.title} description={c.description} rows={c.rows} createLabel={section==="billing"?"Upgrade plan":"Create record"}/>}
