# Generated by Django 4.2.11 on 2026-09-19 17:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="billing_inv_organiz_527da0_idx",
            old_name="billing_inv_organiz_2e57d1_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentevent",
            new_name="billing_pay_organiz_e7cc2a_idx",
            old_name="billing_pay_organiz_67f6aa_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="billing_sub_organiz_e1331c_idx",
            old_name="billing_sub_organiz_1e4e9e_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="billing_sub_current_c59a21_idx",
            old_name="billing_sub_curren_6bc76d_idx",
        ),
        migrations.RenameIndex(
            model_name="usagerecord",
            new_name="billing_usa_organiz_7c0e38_idx",
            old_name="billing_use_organiz_3c3dd1_idx",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="annual_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="monthly_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
