"use client";
import { useMemo, useState } from "react";
import { Plus, Download, Filter, MoreHorizontal } from "lucide-react";
import { Button, Card, EmptyState, FormField, Modal, PageHeader, SearchBox, Status, Wizard } from "./ui";

export type Row = { id:string; name:string; meta:string; status?:string; tone?:"active"|"warning"|"critical"|"neutral"|"info"; extra?:string };
export function DataWorkspace({ title, description, rows, columns=["Record","Context","Status","Action"], createLabel="Create record", onCreate, detailHref }: {title:string;description:string;rows:Row[];columns?:string[];createLabel?:string;onCreate?:()=>void;detailHref?:(id:string)=>string}) {
 const [q,setQ]=useState(""); const filtered=useMemo(()=>rows.filter(r=>`${r.id} ${r.name} ${r.meta} ${r.extra??""}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <div className="content"><PageHeader title={title} description={description} action={<div className="actions"><Button><Download size={14}/> Export</Button><Button><Filter size={14}/> Filters</Button><Button primary onClick={onCreate}><Plus size={14}/> {createLabel}</Button></div>}/><Card><div className="toolbar"><SearchBox value={q} onChange={setQ} placeholder={`Search ${title.toLowerCase()}...`}/><span>{filtered.length} records</span></div>{filtered.length?<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{detailHref?<a href={detailHref(r.id)}><b>{r.id}</b></a>:<b>{r.id}</b>}<div className="muted">{r.name}</div></td><td>{r.meta}</td><td>{r.status&&<Status tone={r.tone}>{r.status}</Status>}</td><td><button className="icon-button"><MoreHorizontal size={15}/></button></td></tr>)}</tbody></table></div>:<EmptyState title="No matching records" description="Adjust your search or filters, or create a new record." action={<Button primary onClick={onCreate}><Plus size={14}/> {createLabel}</Button>}/>}</Card></div>;
}

export function CreateStudyWizard({ onClose }: {onClose:()=>void}) { const [step,setStep]=useState(0); const [saved,setSaved]=useState(false); const steps=["Study details","Protocol","Product & batch","Storage","Timepoints","Tests","Review"]; return <Modal title="Create stability study" onClose={onClose}><Wizard steps={steps} active={step} onSelect={setStep}/>{saved?<div className="success-panel"><div className="success-icon">✓</div><h3>Study created</h3><p>STB-2026-0043 is ready for controlled review.</p><Button primary onClick={onClose}>Open study</Button></div>:<div className="wizard-body"><div className="form-grid"><FormField label="Study title" required><input defaultValue="Amoxicillin long-term stability"/></FormField><FormField label="Study type"><select><option>Long-term</option><option>Accelerated</option><option>Photostability</option></select></FormField><FormField label="Protocol" required><select><option>STB-PRO-003 · v2.1 · Effective</option></select></FormField><FormField label="Specification" required><select><option>SPEC-019 · v3 · Effective</option></select></FormField><FormField label="Site" required><select><option>Cairo Manufacturing Site</option></select></FormField><FormField label="Storage condition"><input defaultValue="25°C / 60% RH"/></FormField></div><div className="wizard-footer"><Button onClick={()=>step>0&&setStep(step-1)}>Back</Button>{step<steps.length-1?<Button primary onClick={()=>setStep(step+1)}>Continue</Button>:<Button primary onClick={()=>setSaved(true)}>Create study</Button>}</div></div>}</Modal> }
