import { useEffect, useState } from "react";
import { api, endpoints, type ApiEnvelope } from "@/lib/api";
import { DataTable } from "@/components/ui/DataTable";
import { ErrorBanner } from "@/components/ui/ErrorBanner";
import { useAuth } from "@/components/AuthProvider";

type M={id:string;name:string;version:string;effective_date:string;status:string;approved_by_name?:string;approved_at?:string;tests?:Test[]};
type Test={id:string;name:string;method:string;specification:string;unit:string;sequence:number};

function unwrap<T>(x:any):T{return x?.data??x;}

export default function Monographs(){
 const { user }=useAuth();
 const [rows,setRows]=useState<M[]>([]),[selected,setSelected]=useState<M|null>(null),[error,setError]=useState(""),[open,setOpen]=useState(false),[password,setPassword]=useState(""),[reason,setReason]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({name:"",version:"",effective_date:""});
 const load=async()=>{try{const p=await api<ApiEnvelope<M[]>>(endpoints.monographs);setRows(unwrap<M[]>(p)||[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load monographs.");}};
 useEffect(()=>{void load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api(endpoints.monographs,{method:"POST",body:JSON.stringify(form)});setForm({name:"",version:"",effective_date:""});setOpen(false);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to create monograph.");}finally{setBusy(false);}};
 const verify=async()=>{const p=await api<ApiEnvelope<{signature_token:string}>>(endpoints.signatureVerify,{method:"POST",body:JSON.stringify({password})});return unwrap<{signature_token:string}>(p).signature_token;};
 const approve=async()=>{if(!selected)return;setBusy(true);setError("");try{const token=await verify();await api(endpoints.monographApprove(selected.id),{method:"POST",headers:{"X-Signature-Token":token},body:JSON.stringify({reason})});setPassword("");setReason("");setSelected(null);await load();}catch(x){setError(x instanceof Error?x.message:"Approval failed.");}finally{setBusy(false);}};
 const addTest=async()=>{if(!selected)return;const name=window.prompt("Test name");if(!name)return;const method=window.prompt("Method")||"";const specification=window.prompt("Specification")||"";const unit=window.prompt("Unit")||"";try{await api(endpoints.monographTests(selected.id),{method:"POST",body:JSON.stringify({name,method,specification,unit,sequence:(selected.tests?.length||0)+1})});await load();}catch(x){setError(x instanceof Error?x.message:"Unable to add test.");}};
 return <div className="content"><div className="page-header"><div><span className="eyebrow">MASTER DATA</span><h1>Monographs</h1><p>Draft monographs can be edited and tested; approval is a signed backend-controlled action.</p></div><button className="btn primary" onClick={()=>setOpen(!open)}>{open?"Close":"New monograph"}</button></div>
 {error&&<ErrorBanner message={error} onRetry={load}/>} 
 {open&&<section className="card form-card" style={{maxWidth:760,marginBottom:14}}><form onSubmit={create}><div className="form-grid"><label className="field"><span>Name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Version</span><input required value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label className="field"><span>Effective date</span><input required type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label></div><button className="btn primary" disabled={busy}>{busy?"Saving…":"Create draft"}</button></form></section>}
 <section className="card table-card"><div className="card-header"><div><strong>{rows.length} monographs</strong><span>Live organization-scoped records</span></div><button className="btn" onClick={()=>void load()}>Refresh</button></div><DataTable rows={rows} columns={[{key:"name",label:"Monograph",sortable:true},{key:"version",label:"Version"},{key:"effective_date",label:"Effective"},{key:"status",label:"Status"},{key:"approved_by_name",label:"Approved by"}]} onRowClick={r=>setSelected(r)} emptyTitle="No monographs" emptyText="Create the first draft monograph for this organization." /></section>
 {selected&&<div className="modal-backdrop"><section className="signature-panel"><span className="eyebrow">MONOGRAPH</span><h2>{selected.name} v{selected.version}</h2><p>Status: <b>{selected.status}</b>. Tests: {selected.tests?.length||0}.</p>{selected.status!=="approved"&&<><button className="btn" onClick={()=>void addTest()}>Add test</button><div className="form-section-title" style={{marginTop:18}}><span>Approval signature</span></div><label className="field"><span>Password re-authentication</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><label className="field"><span>Approval reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)} /></label><div className="modal-actions"><button className="btn" onClick={()=>setSelected(null)}>Close</button><button className="btn approve" disabled={busy||!password||!reason} onClick={()=>void approve()}>{busy?"Approving…":"Approve & sign"}</button></div></>}{selected.status==="approved"&&<div className="modal-actions"><button className="btn" onClick={()=>setSelected(null)}>Close</button></div>}</section></div>}
 </div>;
}