"use client";
import { useState } from "react";
import { CheckCircle2, ChevronRight, CircleAlert, LockKeyhole, Plus, Save, Search, ShieldCheck, X } from "lucide-react";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function Button({ children, primary=false, onClick, type="button" }: {children: React.ReactNode; primary?: boolean; onClick?:()=>void; type?: "button"|"submit"}) { return <button type={type} className={`btn ${primary ? "primary" : ""}`} onClick={onClick}>{children}</button>; }
export function Status({ children, tone="neutral" }: {children: React.ReactNode; tone?: "active"|"warning"|"critical"|"neutral"|"info"}) { return <span className={`badge ${tone}`}>{children}</span>; }
export function Card({ children, className="" }: {children: React.ReactNode; className?: string}) { return <section className={`card ${className}`}>{children}</section>; }
export function EmptyState({ title, description, action }: {title:string; description:string; action?:React.ReactNode}) { return <div className="empty"><div className="empty-icon"><Search size={18}/></div><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function Modal({ title, children, onClose }: {title:string; children:React.ReactNode; onClose:()=>void}) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><strong>{title}</strong><span>Changes are validated before submission.</span></div><button className="icon-button" onClick={onClose}><X size={16}/></button></div>{children}</div></div>; }
export function Wizard({ steps, active, onSelect }: {steps:string[]; active:number; onSelect?:(n:number)=>void}) { return <div className="wizard">{steps.map((step,i)=><button key={step} className={i===active?"current":i<active?"done":""} onClick={()=>onSelect?.(i)}><span>{i<active?<CheckCircle2 size={15}/>:i+1}</span>{step}{i<steps.length-1&&<ChevronRight size={14}/>}</button>)}</div>; }
export function FormField({ label, required, children, hint }: {label:string; required?:boolean; children:React.ReactNode; hint?:string}) { return <label className="field"><span>{label}{required&&<em> *</em>}</span>{children}{hint&&<small>{hint}</small>}</label>; }
export function Toast({ message, kind="success", onClose }: {message:string; kind?:"success"|"error"; onClose:()=>void}) { return <div className={`toast ${kind}`}><span>{kind === "success"?<CheckCircle2 size={17}/>:<CircleAlert size={17}/>}</span>{message}<button onClick={onClose}><X size={14}/></button></div>; }
export function LockedBanner({ children="This record is locked. Changes require a controlled correction workflow." }: {children?:React.ReactNode}) { return <div className="locked"><LockKeyhole size={16}/><span>{children}</span></div>; }
export function SearchBox({ value, onChange, placeholder="Search..." }: {value:string; onChange:(v:string)=>void; placeholder?:string}) { return <div className="table-search"><Search size={15}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>; }
