[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py tests_*.py tests.py
python_classes = Test*
python_functions = test_*
asyncio_default_fixture_loop_scope = function
asyncio_default_test_loop_scope = function
addopts = 
    --cov=.
    --cov-report=term-missing
    --cov-fail-under=90
    -v