# Generated by Django 4.2.11 on 2026-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('qa_manager', 'QA Manager'), ('supervisor', 'Supervisor'), ('analyst', 'Analyst'), ('system', 'System')], default='analyst', max_length=20),
        ),
    ]
