# Generated by Django 4.2.11 on 2026-09-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by repeated failed logins. Expires on its own — see LOCKOUT_MINUTES.",
                null=True,
            ),
        ),
    ]
