"use client";
import {useEffect,useState} from "react";
import {api,endpoints,type ApiEnvelope} from "@/lib/api";
import {ErrorBanner} from "@/components/ui/ErrorBanner";

type Plan={id:string;name:string;code:string;monthly_price:string;annual_price:string;currency:string;max_users:number|null;max_sites:number|null;max_studies:number|null;max_storage_mb:number|null;api_access:boolean};
type Subscription={id:string;status:string;interval:string;trial_ends_at:string|null;current_period_end:string|null;plan:Plan};
type Usage={id:string;metric:string;quantity:number;period_start:string;period_end:string};

export default function Billing(){
 const [plans,setPlans]=useState<Plan[]>([]),[sub,setSub]=useState<Subscription|null>(null),[usage,setUsage]=useState<Usage[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError("");try{const [p,s,u]=await Promise.all([api<ApiEnvelope<Plan[]>>(endpoints.plans),api<ApiEnvelope<Subscription[]>>(endpoints.billing),api<ApiEnvelope<Usage[]>>(endpoints.usage)]);setPlans(p.data||[]);const rows=Array.isArray(s.data)?s.data:(s.data?[s.data] as any:[]);setSub(rows[0]||null);setUsage(u.data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load billing.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 return <div className="content"><div className="page-header"><div><span className="eyebrow">BILLING</span><h1>Subscription & usage</h1><p>Billing state is read from the authoritative backend. The browser never marks a payment as successful.</p></div><button className="btn" onClick={()=>void load()}>Refresh</button></div>{error&&<ErrorBanner message={error} onRetry={load}/>}<div className="grid-2"><section className="card detail-card"><h3>Current subscription</h3>{loading?<div className="empty">Loading…</div>:sub?<><dl><dt>Plan</dt><dd>{sub.plan?.name||"—"}</dd><dt>Status</dt><dd><span className="status active">{sub.status}</span></dd><dt>Interval</dt><dd>{sub.interval}</dd><dt>Trial ends</dt><dd>{sub.trial_ends_at?new Date(sub.trial_ends_at).toLocaleString():"—"}</dd><dt>Period ends</dt><dd>{sub.current_period_end?new Date(sub.current_period_end).toLocaleString():"—"}</dd></dl></>:<div className="empty"><b>No active subscription</b><span>Contact your administrator or complete the approved billing flow.</span></div>}</section><section className="card detail-card"><h3>Usage</h3>{usage.length?<div className="list">{usage.map(x=><div className="list-row" key={x.id}><div><b>{x.metric}</b><span>{new Date(x.period_start).toLocaleDateString()} → {new Date(x.period_end).toLocaleDateString()}</span></div><strong>{x.quantity}</strong></div>)}</div>:<div className="empty"><b>No usage records</b><span>No usage data was returned for the current workspace.</span></div>}</section></div><section className="card table-card"><div className="card-header"><div><strong>Available plans</strong><span>Catalog data only. Plan changes require the provider-backed billing workflow.</span></div></div><div className="table-wrap"><table><thead><tr><th>Plan</th><th>Monthly</th><th>Annual</th><th>Users</th><th>Sites</th><th>Studies</th><th>API</th></tr></thead><tbody>{plans.map(x=><tr key={x.id}><td><b>{x.name}</b><div style={{fontSize:9,color:"var(--muted)"}}>{x.code}</div></td><td>{x.currency} {x.monthly_price}</td><td>{x.currency} {x.annual_price}</td><td>{x.max_users??"Unlimited"}</td><td>{x.max_sites??"Unlimited"}</td><td>{x.max_studies??"Unlimited"}</td><td>{x.api_access?"Enabled":"Not included"}</td></tr>)}</tbody></table></div></section><div className="security-band compact"><span><strong>Payment safety boundary.</strong> Checkout and subscription activation are only accepted from verified provider events; this UI does not simulate success.</span></div></div>
}