# Generated by Django 4.2.11 on 2026-09-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
        ("chamber", "0002_add_organization_boundary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="samplepull",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
    ]
