"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, endpoints, type ApiEnvelope } from "@/lib/api";
import { ErrorBanner } from "@/components/ui/ErrorBanner";

type Dashboard = { summary?: Record<string, number>; quality?: Record<string, number>; };
type Analytics = {
  results: Array<{pass_fail:string;count:number}>;
  batches: Array<{status:string;count:number}>;
  test_points: Array<{month:string|null;status:string;count:number}>;
  quality: Array<{kind:string;status:string;count:number}>;
};

export default function Reports() {
  const [data,setData]=useState<Dashboard|null>(null);
  const [error,setError]=useState("");
  const [analytics,setAnalytics]=useState<Analytics|null>(null);

  const load=async()=>{try{setError("");const [r,a]=await Promise.all([api<ApiEnvelope<Dashboard>>(endpoints.dashboard),api<ApiEnvelope<Analytics>>(endpoints.analytics)]);setData(r.data);setAnalytics(a.data)}catch(e){setError(e instanceof Error?e.message:"Unable to load reporting data.")}};
  useEffect(()=>{void load()},[]);

  const exportUrl=(resource:string)=>`${(process.env.NEXT_PUBLIC_API_URL??"/api/backend").replace(/\/$/,"")}${endpoints.exports}?resource=${encodeURIComponent(resource)}`;

  return <div className="content">
    <div className="page-header"><div><span className="eyebrow">REPORTING</span><h1>Reports & exports</h1><p>Operational metrics and tenant-scoped CSV exports from the live backend.</p></div><button className="btn" onClick={()=>void load()}>Refresh</button></div>
    {error&&<ErrorBanner message={error} onRetry={load}/>}
    <div className="stats">
      {[["Active batches","active_batches"],["Completed batches","completed_batches"],["Failed batches","failed_batches"],["Overdue tests","overdue_tests"],["Submitted results","submitted_results"],["Approved results","approved_results"],["OOS open","oos_open"],["CAPA open","capa_open"]].map(([label,key])=><div className="stat-card" key={key}><span>{label}</span><strong>{data?.summary?.[key]??data?.quality?.[key]??"—"}</strong><small>Authorized organization data</small></div>)}
    </div>

    <section className="card table-card">
      <div className="card-header"><div><strong>Operational analytics</strong><span>Tenant-scoped aggregates from the live database.</span></div></div>
      <div className="feature-grid" style={{padding:"16px"}}>
        <div className="feature-card"><h3>Result distribution</h3>{analytics?.results.map(x=><div className="metric-row" key={x.pass_fail}><span>{x.pass_fail}</span><strong>{x.count}</strong></div>) ?? <p>Loading…</p>}</div>
        <div className="feature-card"><h3>Batch status</h3>{analytics?.batches.map(x=><div className="metric-row" key={x.status}><span>{x.status}</span><strong>{x.count}</strong></div>) ?? <p>Loading…</p>}</div>
        <div className="feature-card"><h3>Quality events</h3>{analytics?.quality.slice(0,10).map((x,i)=><div className="metric-row" key={x.kind+x.status+i}><span>{x.kind} · {x.status}</span><strong>{x.count}</strong></div>) ?? <p>Loading…</p>}</div>
      </div>
      <div className="table-wrap"><table><thead><tr><th>Month</th><th>Status</th><th>Test points</th></tr></thead><tbody>{analytics?.test_points.map((x,i)=><tr key={x.month+x.status+i}><td>{x.month||"—"}</td><td>{x.status}</td><td>{x.count}</td></tr>)}</tbody></table>{!analytics?.test_points.length&&<div className="empty">No time-series test-point data yet.</div>}</div>
    </section>

    <section className="card"><div className="card-header"><div><strong>Controlled exports</strong><span>CSV files are generated by Django using the current tenant context.</span></div></div><div className="feature-grid" style={{padding:"16px"}}>{[["Results","results"],["Batches","batches"],["Test points","test-points"],["Quality events","quality"]].map(([label,resource])=><a className="feature-card" key={resource} href={exportUrl(resource)}><h3>{label}</h3><p>Download the current authorized dataset as CSV.</p><span className="btn">Export CSV →</span></a>)}</div></section>
    <div className="security-band compact"><span><strong>Report integrity.</strong> Export scope is controlled by the backend organization boundary; the browser does not select another tenant.</span></div>
  </div>;
}
