"use client";

import { useEffect, useState } from "react";
import { api, endpoints, type ApiEnvelope } from "@/lib/api";
import { ErrorBanner } from "@/components/ui/ErrorBanner";

type Batch={id:string;batch_number:string;product_name:string;location:string;qty_remaining:number;status:string};

export default function Chambers(){
 const [batches,setBatches]=useState<Batch[]>([]),[selected,setSelected]=useState(""),[shelf,setShelf]=useState(""),[rack,setRack]=useState(""),[position,setPosition]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await api<ApiEnvelope<Batch[]>>(endpoints.chambers);setBatches(r.data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load chamber inventory.")}};
 useEffect(()=>{void load()},[]);
 const move=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{await api(endpoints.locationMove,{method:"POST",body:JSON.stringify({batch:selected,new_shelf:shelf,new_rack:rack,new_position:position,reason})});setMessage("Batch location changed and the movement was audit logged.");setSelected("");setShelf("");setRack("");setPosition("");setReason("");await load()}catch(x){setError(x instanceof Error?x.message:"Unable to move batch.")}finally{setBusy(false)}};
 return <div className="content"><div className="page-header"><div><span className="eyebrow">CHAMBER MANAGEMENT</span><h1>Chamber inventory</h1><p>View batch positions and execute controlled location movements with an audit reason.</p></div></div>{error&&<ErrorBanner message={error} onRetry={load}/>} {message&&<div className="form-success">{message}</div>}<div className="grid-2"><section className="card form-card"><h3>Move batch</h3><form onSubmit={move}><label className="field"><span>Batch</span><select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select batch…</option>{batches.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.batch_number} · {x.product_name} · {x.location||"Unassigned"}</option>)}</select></label><div className="form-grid"><label className="field"><span>Shelf</span><input required value={shelf} onChange={e=>setShelf(e.target.value)}/></label><label className="field"><span>Rack</span><input required value={rack} onChange={e=>setRack(e.target.value)}/></label><label className="field"><span>Position</span><input required value={position} onChange={e=>setPosition(e.target.value)}/></label></div><label className="field"><span>Reason</span><textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn primary" disabled={busy}>{busy?"Recording…":"Move batch"}</button></form></section><section className="card detail-card"><h3>Control boundary</h3><p>Location uniqueness, tenant ownership and history are enforced by Django inside a database transaction.</p><div className="security-note">Every successful movement creates a location-history record and audit entry.</div></section></div><section className="card table-card"><div className="card-header"><div><strong>{batches.length} batches</strong><span>Current authorized chamber inventory</span></div><button className="btn" onClick={()=>void load()}>Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Batch</th><th>Product</th><th>Location</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{batches.map(x=><tr key={x.id}><td><b>{x.batch_number}</b></td><td>{x.product_name}</td><td>{x.location||"—"}</td><td>{x.qty_remaining}</td><td><span className={"status "+(x.status==="active"?"active":"critical")}>{x.status}</span></td></tr>)}</tbody></table>{!batches.length&&!error&&<div className="empty"><b>No chamber inventory</b><span>No authorized active batch inventory was returned.</span></div>}</div></section></div>;
}
