# Generated for QCSTS stability-domain v2.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform", "0001_initial"),
        ("products", "0001_initial"),
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageCondition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("temperature_min_c", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("temperature_max_c", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("humidity_min_rh", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("humidity_max_rh", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("effective", "Effective"), ("superseded", "Superseded"), ("inactive", "Inactive")], default="draft", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_storagecondition_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_storagecondition_records", to="platform.organization")),
            ],
            options={"db_table": "stability_storage_condition", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=255)),
                ("study_type", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("effective", "Effective"), ("superseded", "Superseded"), ("inactive", "Inactive")], default="draft", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_protocol_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_protocol_records", to="platform.organization")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stability_protocols", to="products.product")),
            ],
            options={"db_table": "stability_protocol", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("effective", "Effective"), ("superseded", "Superseded"), ("inactive", "Inactive")], default="draft", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_specification_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_specification_records", to="platform.organization")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stability_specifications", to="products.product")),
            ],
            options={"db_table": "stability_specification", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="ProtocolVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.CharField(max_length=50)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("effective", "Effective"), ("superseded", "Superseded"), ("inactive", "Inactive")], default="draft", max_length=20)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_protocol_versions", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_protocolversion_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_protocolversion_records", to="platform.organization")),
                ("protocol", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="stability.protocol")),
            ],
            options={"db_table": "stability_protocol_version", "ordering": ["protocol", "-version"]},
        ),
        migrations.CreateModel(
            name="SpecificationVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.CharField(max_length=50)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("effective", "Effective"), ("superseded", "Superseded"), ("inactive", "Inactive")], default="draft", max_length=20)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_specification_versions", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_specificationversion_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_specificationversion_records", to="platform.organization")),
                ("specification", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="stability.specification")),
            ],
            options={"db_table": "stability_specification_version", "ordering": ["specification", "-version"]},
        ),
        migrations.CreateModel(
            name="StabilityStudy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("study_type", models.CharField(max_length=40)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_end_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("planned", "Planned"), ("active", "Active"), ("completed", "Completed"), ("closed", "Closed"), ("canceled", "Canceled")], default="draft", max_length=20)),
                ("objective", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_stabilitystudy_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_stabilitystudy_records", to="platform.organization")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stability_studies", to="products.product")),
                ("protocol_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="studies", to="stability.protocolversion")),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stability_studies", to="platform.site")),
            ],
            options={"db_table": "stability_study", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="StudyBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("planned_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_studybatch_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_studybatch_records", to="platform.organization")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stability_enrollments", to="batches.batch")),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="study_batches", to="stability.stabilitystudy")),
            ],
            options={"db_table": "stability_study_batch"},
        ),
        migrations.CreateModel(
            name="StudyTimepoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=50)),
                ("nominal_days", models.PositiveIntegerField()),
                ("target_date", models.DateField()),
                ("tolerance_days", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("open", "Open"), ("completed", "Completed"), ("canceled", "Canceled")], default="planned", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_studytimepoint_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_studytimepoint_records", to="platform.organization")),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="timepoints", to="stability.stabilitystudy")),
            ],
            options={"db_table": "stability_study_timepoint", "ordering": ["nominal_days", "code"]},
        ),
        migrations.CreateModel(
            name="StabilitySample",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sample_code", models.CharField(max_length=120)),
                ("quantity", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("stored", "Stored"), ("pulled", "Pulled"), ("testing", "Testing"), ("completed", "Completed"), ("disposed", "Disposed"), ("retained", "Retained")], default="stored", max_length=20)),
                ("chamber_reference", models.CharField(blank=True, max_length=120)),
                ("location_reference", models.CharField(blank=True, max_length=120)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stability_stabilitysample_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stability_stabilitysample_records", to="platform.organization")),
                ("storage_condition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="samples", to="stability.storagecondition")),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="samples", to="stability.stabilitystudy")),
                ("study_batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="samples", to="stability.studybatch")),
                ("timepoint", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="samples", to="stability.studytimepoint")),
            ],
            options={"db_table": "stability_sample", "ordering": ["sample_code"]},
        ),
        migrations.AddConstraint(model_name="storagecondition", constraint=models.UniqueConstraint(fields=["organization", "code"], name="storage_condition_code_per_org")),
        migrations.AddConstraint(model_name="protocol", constraint=models.UniqueConstraint(fields=["organization", "code"], name="protocol_code_per_org")),
        migrations.AddConstraint(model_name="specification", constraint=models.UniqueConstraint(fields=["organization", "code"], name="specification_code_per_org")),
        migrations.AddConstraint(model_name="protocolversion", constraint=models.UniqueConstraint(fields=["protocol", "version"], name="protocol_version_unique")),
        migrations.AddConstraint(model_name="specificationversion", constraint=models.UniqueConstraint(fields=["specification", "version"], name="specification_version_unique")),
        migrations.AddConstraint(model_name="stabilitystudy", constraint=models.UniqueConstraint(fields=["organization", "code"], name="study_code_per_org")),
        migrations.AddConstraint(model_name="studybatch", constraint=models.UniqueConstraint(fields=["study", "batch"], name="study_batch_unique")),
        migrations.AddConstraint(model_name="studytimepoint", constraint=models.UniqueConstraint(fields=["study", "code"], name="study_timepoint_code_unique")),
        migrations.AddConstraint(model_name="stabilitysample", constraint=models.UniqueConstraint(fields=["organization", "sample_code"], name="sample_code_per_org")),
    ]
