# Generated by Django 4.2.11 on 2026-09-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stability", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="protocolversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="protocolversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="protocolversion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="protocolversion",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="protocolversion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="protocolversion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="specificationversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="specificationversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="specificationversion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="specificationversion",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="specificationversion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="specificationversion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitysample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitysample",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stabilitysample",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stabilitysample",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitysample",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitysample",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitystudy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitystudy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stabilitystudy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stabilitystudy",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitystudy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="stabilitystudy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="storagecondition",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="storagecondition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storagecondition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="storagecondition",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="storagecondition",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="storagecondition",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="studybatch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="studybatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studybatch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="studybatch",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="studybatch",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="studybatch",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
        migrations.AlterField(
            model_name="studytimepoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created. Set by server, never editable.",
            ),
        ),
        migrations.AlterField(
            model_name="studytimepoint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studytimepoint",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record. Auto-generated UUID.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="studytimepoint",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
            ),
        ),
        migrations.AlterField(
            model_name="studytimepoint",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="platform.organization",
            ),
        ),
        migrations.AlterField(
            model_name="studytimepoint",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last modification. Updated automatically on every save.",
            ),
        ),
    ]
