"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api, endpoints, type ApiEnvelope } from "@/lib/api";
import { Card, PageHeader, Status, Button, LockedBanner } from "@/components/ui";
import { ErrorBanner } from "@/components/ui/ErrorBanner";

type Study = { id:string; code:string; name:string; status:string; study_type:string; site:string; product:string; protocol_version:string; start_date?:string|null; target_end_date?:string|null; objective?:string };
type Timepoint = { id:string; code:string; nominal_days:number; target_date:string; status:string };
type Sample = { id:string; sample_code:string; quantity:number; status:string; chamber_reference?:string; location_reference?:string };
type Enrollment = { id:string; batch:string; enrolled_at?:string|null; planned_quantity?:number|null };

export default function StudyDetail(){
 const {id}=useParams<{id:string}>(); const [study,setStudy]=useState<Study|null>(null); const [timepoints,setTimepoints]=useState<Timepoint[]>([]); const [samples,setSamples]=useState<Sample[]>([]); const [batches,setBatches]=useState<Enrollment[]>([]); const [tab,setTab]=useState("Overview"); const [error,setError]=useState("");
 const load=async()=>{try{setError("");const [s,t,sm,b]=await Promise.all([api<ApiEnvelope<Study>>(endpoints.studies+"/"+id+"/"),api<ApiEnvelope<Timepoint[]>>(endpoints.timePoints+"?study="+id),api<ApiEnvelope<Sample[]>>(endpoints.samples+"?study="+id),api<ApiEnvelope<Enrollment[]>>(endpoints.studyBatches+"?study="+id)]);setStudy(s.data);setTimepoints(t.data||[]);setSamples(sm.data||[]);setBatches(b.data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load study.")}};
 useEffect(()=>{load()},[id]);
 if(error&&!study)return <div className="content"><ErrorBanner message={error} onRetry={load}/></div>;
 if(!study)return <div className="content"><div className="empty">Loading study…</div></div>;
 const completed=timepoints.filter(x=>x.status==="completed").length; const activeSamples=samples.filter(x=>x.status!=="disposed").length;
 return <div className="content"><PageHeader eyebrow="Stability Study" title={study.code+" · "+study.name} description={study.study_type+" · "+(study.objective||"Controlled stability program")} action={<div className="actions"><Button onClick={()=>window.location.href="/api/v1/reports/export.csv?resource=results"}>Export</Button></div>}/>
 <div className="detail-banner"><div><Status tone={study.status==="active"?"active":"warning"}>{study.status.replaceAll("_"," ").toUpperCase()}</Status><strong>{study.name}</strong><span>Site {study.site} · Product {study.product}</span></div><div className="detail-kpis"><b>{completed}<small>completed timepoints</small></b><b>{activeSamples}<small>active samples</small></b><b>{batches.length}<small>enrolled batches</small></b></div></div>
 <div className="tabs">{["Overview","Timepoints","Samples","Batches"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
 {error&&<ErrorBanner message={error} onRetry={load}/>}
 {tab==="Overview"&&<div className="grid-2"><Card><div className="card-header"><strong>Controlled study record</strong><span>Tenant scoped</span></div><dl className="detail-list"><dt>Status</dt><dd>{study.status}</dd><dt>Study type</dt><dd>{study.study_type}</dd><dt>Start</dt><dd>{study.start_date||"—"}</dd><dt>Target end</dt><dd>{study.target_end_date||"—"}</dd><dt>Protocol version</dt><dd>{study.protocol_version}</dd></dl></Card><Card><div className="card-header"><strong>Workflow controls</strong><span>Server-side lifecycle</span></div><LockedBanner>Lifecycle state changes are controlled by the backend. Approval, completion and closure require signature authentication and are audit logged.</LockedBanner><div className="actions"><Button primary>Open transition queue</Button></div></Card></div>}
 {tab==="Timepoints"&&<Card><div className="card-header"><strong>Study timepoints</strong><span>{timepoints.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Code</th><th>Nominal days</th><th>Target</th><th>Status</th></tr></thead><tbody>{timepoints.map(x=><tr key={x.id}><td><b>{x.code}</b></td><td>{x.nominal_days}</td><td>{x.target_date}</td><td><Status tone={x.status==="completed"?"active":"warning"}>{x.status}</Status></td></tr>)}</tbody></table>{!timepoints.length&&<div className="empty">No timepoints are attached to this study.</div>}</div></Card>}
 {tab==="Samples"&&<Card><div className="card-header"><strong>Study samples</strong><span>{samples.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Sample</th><th>Quantity</th><th>Status</th><th>Chamber</th><th>Location</th></tr></thead><tbody>{samples.map(x=><tr key={x.id}><td><b>{x.sample_code}</b></td><td>{x.quantity}</td><td><Status tone={x.status==="completed"||x.status==="retained"?"active":"warning"}>{x.status}</Status></td><td>{x.chamber_reference||"—"}</td><td>{x.location_reference||"—"}</td></tr>)}</tbody></table>{!samples.length&&<div className="empty">No samples are attached to this study.</div>}</div></Card>}
 {tab==="Batches"&&<Card><div className="card-header"><strong>Enrolled batches</strong><span>{batches.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Batch</th><th>Enrolled</th><th>Planned quantity</th></tr></thead><tbody>{batches.map(x=><tr key={x.id}><td><b>{x.batch}</b></td><td>{x.enrolled_at||"—"}</td><td>{x.planned_quantity??"—"}</td></tr>)}</tbody></table>{!batches.length&&<div className="empty">No batches are enrolled in this study.</div>}</div></Card>}</div>
}