"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api, type ApiEnvelope } from "@/lib/api";

type TestPoint={id:string;batch:string;batch_number?:string;product_name?:string;month:number;scheduled_date:string;status:string;completed_at?:string|null};

export default function SchedulePage(){
 const [rows,setRows]=useState<TestPoint[]>([]);
 const [filter,setFilter]=useState("pending");
 const [error,setError]=useState("");
 const [loading,setLoading]=useState(true);

 const load=async()=>{
  setLoading(true);setError("");
  try{
   const path="/test-points/"+(filter?"?status="+encodeURIComponent(filter):"");
   const r=await api<ApiEnvelope<TestPoint[]>>(path);
   setRows(Array.isArray(r.data)?r.data:[]);
  }catch(v){setError(v instanceof Error?v.message:"Unable to load scheduled test points.")}finally{setLoading(false)}
 };
 useEffect(()=>{void load()},[filter]);

 return <div className="content">
  <div className="page-header"><div><span className="eyebrow">STABILITY EXECUTION</span><h1>Test points</h1><p>Read-only schedule generated by the backend from batch study type and incubation date.</p></div><button className="btn" onClick={()=>void load()}>Refresh</button></div>
  <div className="filter-bar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="overdue">Overdue</option><option value="completed">Completed</option><option value="failed">Failed</option></select></div>
  {error&&<div className="inline-error">{error}</div>}
  <section className="card table-card"><div className="table-wrap"><table><thead><tr><th>Batch</th><th>Product</th><th>Month</th><th>Scheduled</th><th>Status</th><th/></tr></thead><tbody>{rows.map(tp=><tr key={tp.id}><td><b>{tp.batch_number||tp.batch}</b></td><td>{tp.product_name||"—"}</td><td>{tp.month===0?"Initial":tp.month+"M"}</td><td>{tp.scheduled_date}</td><td><span className={"status "+(tp.status==="completed"?"active":tp.status==="overdue"||tp.status==="failed"?"critical":"warning")}>{tp.status}</span></td><td><Link className="btn" href={"/app/test-entry/"+tp.id}>Enter results</Link></td></tr>)}</tbody></table>{loading&&<div className="empty">Loading test points…</div>}{!loading&&!rows.length&&<div className="empty">No test points returned for this status.</div>}</div></section>
 </div>
}
